# Generated by Django 4.1.2 on 2022-10-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_data',
            field=models.JSONField(default=dict, help_text='Contact data will be available for use in flow templates', verbose_name='contact data'),
        ),
    ]
