# Generated by Django 4.0.3 on 2022-05-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_account_options_alter_environment_options_and_more'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='channel_data',
            field=models.JSONField(default=dict, verbose_name='channel data'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_data',
            field=models.JSONField(default=dict, verbose_name='contact data'),
        ),
        migrations.AddField(
            model_name='contact',
            name='environment',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.environment', verbose_name='environment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='index1',
            field=models.CharField(default='', max_length=100, verbose_name='index 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='index2',
            field=models.CharField(default='', max_length=100, verbose_name='index 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='index3',
            field=models.CharField(default='', max_length=100, verbose_name='index 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='index4',
            field=models.CharField(default='', max_length=100, verbose_name='index 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='index5',
            field=models.CharField(default='', max_length=100, verbose_name='index 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='key',
            field=models.CharField(default='', max_length=100, verbose_name='key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('environment', 'index1'), ('environment', 'index4'), ('environment', 'index2'), ('environment', 'index3'), ('environment', 'key'), ('environment', 'index5')},
        ),
    ]
