# Generated by Django 4.1.3 on 2022-11-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_public_key_alter_contact_contact_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="public_key",
            field=models.CharField(max_length=40, verbose_name="public key"),
        ),
    ]
