# Generated by Django 4.0.3 on 2022-05-12 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_account_options_alter_environment_options_and_more'),
        ('contacts', '0002_contact_channel_data_contact_contact_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['environment', 'index1'], name='contacts_co_environ_0451c4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['environment', 'index2'], name='contacts_co_environ_711e13_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['environment', 'index3'], name='contacts_co_environ_058565_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['environment', 'index4'], name='contacts_co_environ_007576_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['environment', 'index5'], name='contacts_co_environ_e297c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('environment'), django.db.models.expressions.F('key'), name='key_environment'),
        ),
    ]
