# Generated by Django 4.0.3 on 2022-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_unique_together_contact_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='index6',
            field=models.CharField(default='', max_length=100, verbose_name='index 6'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['environment', 'index6'], name='contacts_co_environ_de5957_idx'),
        ),
    ]
