# Generated by Django 4.0.4 on 2022-05-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_index6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='index1',
            field=models.CharField(blank=True, max_length=100, verbose_name='index 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='index2',
            field=models.CharField(blank=True, max_length=100, verbose_name='index 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='index3',
            field=models.CharField(blank=True, max_length=100, verbose_name='index 3'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='index4',
            field=models.CharField(blank=True, max_length=100, verbose_name='index 4'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='index5',
            field=models.CharField(blank=True, max_length=100, verbose_name='index 5'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='index6',
            field=models.CharField(blank=True, max_length=100, verbose_name='index 6'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.CharField(help_text='Key must be unique to all your contacts', max_length=100, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='This name will be used across informer app', max_length=200, verbose_name='name'),
        ),
    ]
