# Generated by Django 4.0.4 on 2022-05-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
                'ordering': ('account', 'name'),
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailChannel',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configuration.channel')),
                ('host', models.CharField(max_length=100, verbose_name='host')),
                ('port', models.PositiveSmallIntegerField(verbose_name='port')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('password', models.CharField(max_length=150, verbose_name='password')),
            ],
            options={
                'verbose_name': 'email channel',
                'verbose_name_plural': 'email channels',
            },
            bases=('configuration.channel',),
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='configuration.account', verbose_name='account')),
            ],
        ),
    ]
