# Generated by Django 4.0.4 on 2022-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name': 'environment', 'verbose_name_plural': 'environments'},
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('account', 'name')},
        ),
    ]
