# Generated by Django 4.0.4 on 2022-04-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='slug'),
        ),
    ]
