# Generated by Django 4.0.3 on 2022-04-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='slug',
            field=models.SlugField(default='', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
