# Generated by Django 4.0.4 on 2022-05-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_environment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='emailchannel',
            name='account',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environment',
            name='account',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account'),
            preserve_default=False,
        ),
    ]
