# Generated by Django 4.1 on 2022-09-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_user_account'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
