# Generated by Django 4.0.4 on 2022-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_account_emailchannel_account_environment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchannel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
