# Generated by Django 4.0.4 on 2022-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_emailchannel_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchannel',
            name='from_email',
            field=models.EmailField(default='info@gotrendier.com', help_text='Default from address for this channel', max_length=200, verbose_name='from email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailchannel',
            name='security',
            field=models.CharField(choices=[('none', 'None'), ('ssl', 'TSL/SSL'), ('starttls', 'STARTTLS')], default='ssl', max_length=20, verbose_name='security'),
        ),
    ]
