# Generated by Django 4.0.5 on 2022-08-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_emailchannel_from_email_alter_emailchannel_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushChannel',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configuration.channel')),
                ('firebase_credentials', models.JSONField(default=dict, verbose_name='Firebase credentials')),
            ],
            options={
                'verbose_name': 'push channel',
                'verbose_name_plural': 'push channels',
            },
            bases=('configuration.channel',),
        ),
    ]
