# Generated by Django 4.0.5 on 2022-08-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('configuration', '0006_pushchannel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('account', 'content_type'), 'verbose_name': 'channel', 'verbose_name_plural': 'channels'},
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('account', 'content_type')},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
    ]
