# Generated by Django 4.0.5 on 2022-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_channel_options_alter_channel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushchannel',
            name='firebase_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='Firebase credentials'),
        ),
    ]
