version: '3.7'

x-informer-django: &informer-django
  environment:
    - "DEBUG=True"
    - "EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend"
    - "ROLLBAR_TOKEN=9d10822598ac487ba4a6f672d39941d5"
    - "CACHE_URL=locmemcache://"
  build: 
    context: .
    target: "dev"
  volumes:
    - .:/usr/src/app
  depends_on:
    - informer_redis

services:
  informer_app:
    <<: *informer-django
    container_name: informer_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"

  informer_worker:
    <<: *informer-django
    container_name: informer_worker
    command: "python manage.py rundramatiq --reload"   
  
  informer_redis:
    image: redis:alpine
    container_name: informer_redis
