# fly.toml file generated for informer on 2022-10-08T20:29:02+02:00

app = "informer"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "sh /app/fly/app-entrypoint.sh"
workers = "sh /app/fly/workers-entrypoint.sh"

[env]
  ALLOWED_HOSTS = "informer.fly.dev,.dropdatabase.es"
  CACHE_URL = "filecache:////cache"
  STATS_REDIS_URL = "redis://localhost"
  DRAMATIQ_REDIS_URL = "redis://default:6951c47f1d5d4d7d8a03a090ba5d73f7@fly-informer-redis.upstash.io"
  ROLLBAR_ENVIRONMENT = "fly"
  ROLLBAR_CLIENT_TOKEN = "882f4c50682347a8bf598e628144dcbf"
  DEBUG = 0

[build]
  build-target = "prod"

[deploy]
  release_command = "python manage.py migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
