# fly.toml file generated for informer on 2022-10-08T20:29:02+02:00

app = "informer"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ALLOWED_HOSTS = "informer.fly.dev,informer.dropdatabase.es"
  CACHE_URL = "filecache:////cache"
  REDIS_URL = "redis://localhost"
  DATABASE_URL = "sqlite:////data//informer.sqlite"
  SWAP = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data"
  source = "informer_data"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
