# Generated by Django 4.1.2 on 2022-10-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'send email', 'verbose_name_plural': 'email sending'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ('id', '-date'), 'verbose_name': 'flow', 'verbose_name_plural': 'communication flows'},
        ),
        migrations.AlterModelOptions(
            name='push',
            options={'verbose_name': 'send push', 'verbose_name_plural': 'push sending'},
        ),
        migrations.RemoveField(
            model_name='email',
            name='email_channel',
        ),
        migrations.RemoveField(
            model_name='email',
            name='only_unread',
        ),
        migrations.RemoveField(
            model_name='push',
            name='only_unread',
        ),
        migrations.RemoveField(
            model_name='push',
            name='push_channel',
        ),
        migrations.AddField(
            model_name='email',
            name='testing_context',
            field=models.JSONField(default=dict, verbose_name='testing context'),
        ),
        migrations.AddField(
            model_name='push',
            name='testing_context',
            field=models.JSONField(default=dict, verbose_name='testing context'),
        ),
    ]
