# Generated by Django 4.1.2 on 2022-10-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_alter_email_options_alter_flow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='testing_context',
        ),
        migrations.RemoveField(
            model_name='push',
            name='testing_context',
        ),
        migrations.AddField(
            model_name='email',
            name='preview_context',
            field=models.JSONField(default=dict, verbose_name='preview context'),
        ),
        migrations.AddField(
            model_name='push',
            name='preview_context',
            field=models.JSONField(default=dict, verbose_name='preview context'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='contact_key',
            field=models.CharField(max_length=100, verbose_name='contact key'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='event_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='event payload'),
        ),
    ]
