# Generated by Django 4.1.2 on 2022-10-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_remove_email_testing_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='preview_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='preview context'),
        ),
        migrations.AlterField(
            model_name='push',
            name='preview_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='preview context'),
        ),
    ]
