# Generated by Django 4.1.4 on 2023-01-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0004_alter_push_url_alter_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='skip_ssl',
            field=models.BooleanField(default=False, help_text='Allows to connect to insecure webhooks', verbose_name='Skip https certificate validation'),
        ),
    ]
