# Generated by Django 4.1.2 on 2022-10-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0004_alter_email_preview_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('flowstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flows.flowstep')),
                ('url', models.URLField(verbose_name='url')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=6, verbose_name='method')),
                ('contenttype', models.CharField(choices=[('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('application/json', 'application/json'), ('application/xml', 'application/xml'), ('text/plain', 'text/plain'), ('text/html', 'text/html')], max_length=50, verbose_name='Content type')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('preview_context', models.JSONField(blank=True, default=dict, verbose_name='preview context')),
            ],
            options={
                'verbose_name': 'webook',
                'verbose_name_plural': 'webhooks',
            },
            bases=('flows.flowstep',),
        ),
        migrations.AlterModelOptions(
            name='delay',
            options={'verbose_name': 'delay', 'verbose_name_plural': 'delays'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groupings'},
        ),
    ]
