# Generated by Django 4.1.2 on 2022-10-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='private_key',
            field=models.CharField(default=1, max_length=40, unique=True, verbose_name='private key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environment',
            name='public_key',
            field=models.CharField(default=1, max_length=40, unique=True, verbose_name='public key'),
            preserve_default=False,
        ),
    ]
