# Generated by Django 4.1 on 2022-09-01 21:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='id')),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='revision')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('trigger', models.CharField(db_index=True, max_length=150, verbose_name='trigger')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account')),
                ('environments', models.ManyToManyField(editable=False, related_name='pipelines', to='configuration.environment')),
            ],
            options={
                'verbose_name': 'pipeline',
                'verbose_name_plural': 'pipelines',
                'ordering': ('id', '-date'),
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(editable=False, verbose_name='order')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('pipeline', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipelines.pipeline', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'pipeline step',
                'verbose_name_plural': 'pipeline steps',
                'ordering': ('pipeline', 'order'),
                'unique_together': {('pipeline', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('pipelinestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipelines.pipelinestep')),
                ('time', models.DurationField(verbose_name='time')),
            ],
            bases=('pipelines.pipelinestep',),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('pipelinestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipelines.pipelinestep')),
                ('only_unread', models.BooleanField(default=True, help_text='Send notification only if user have not seen it yet', verbose_name='unread only')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('html_body', models.TextField(verbose_name='html body message')),
                ('text_body', models.TextField(help_text="Text used on clients that don't support html emails", verbose_name='plain text message')),
                ('autogenerate_text', models.BooleanField(default=True, help_text='Generate text automatically from html template', verbose_name='autogenerate text')),
                ('from_email', models.EmailField(blank=True, help_text="From address for this step. Overrides channel's default from address", max_length=200, verbose_name='from email')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
            },
            bases=('pipelines.pipelinestep',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('pipelinestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipelines.pipelinestep')),
                ('window', models.DurationField(verbose_name='time window')),
                ('key', models.SlugField(max_length=150, verbose_name='grouping key')),
            ],
            bases=('pipelines.pipelinestep',),
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('pipeline_id', models.UUIDField(editable=False, verbose_name='id')),
                ('contact_key', models.CharField(editable=False, max_length=100, verbose_name='contact key')),
                ('event_payload', models.JSONField(default=dict, editable=False, verbose_name='event payload')),
                ('pipeline_data', models.JSONField(default=dict, verbose_name='pipeline data')),
                ('group_key', models.CharField(blank=True, editable=False, max_length=200, verbose_name='group_key')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account')),
                ('environment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.environment', verbose_name='environment')),
                ('pipeline_revision', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='pipelines.pipeline', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'pipeline run',
                'verbose_name_plural': 'pipeline runs',
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('pipeline_run_id', models.UUIDField(verbose_name='pipeline_run_id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('level', models.CharField(choices=[('DEBUG', 'debug'), ('INFO', 'info'), ('WARNING', 'warning'), ('ERROR', 'error')], default='INFO', max_length=10, verbose_name='level')),
                ('message', models.CharField(max_length=400, verbose_name='message')),
                ('context', models.JSONField(default=dict, verbose_name='context')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account')),
                ('environment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.environment', verbose_name='environment')),
            ],
            options={
                'verbose_name': 'pipeline log',
                'verbose_name_plural': 'pipeline logs',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('pipelinestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipelines.pipelinestep')),
                ('only_unread', models.BooleanField(default=True, help_text='Send notification only if user have not seen it yet', verbose_name='unread only')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('url', models.URLField(verbose_name='url')),
                ('push_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.pushchannel', verbose_name='push channel')),
            ],
            options={
                'verbose_name': 'push template',
                'verbose_name_plural': 'push templates',
            },
            bases=('pipelines.pipelinestep',),
        ),
        migrations.AddConstraint(
            model_name='pipelinerun',
            constraint=models.UniqueConstraint(fields=('contact_key', 'pipeline_revision', 'group_key'), name='unique group'),
        ),
        migrations.AddIndex(
            model_name='pipelinelog',
            index=models.Index(fields=['pipeline_run_id', '-date'], name='pipelines_p_pipelin_edb0af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('id', 'date')},
        ),
        migrations.AddField(
            model_name='email',
            name='email_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.emailchannel', verbose_name='email channel'),
        ),
    ]
