# Generated by Django 4.0.4 on 2022-04-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='autogenerate_text',
            field=models.BooleanField(default=True, verbose_name='autogenerate text'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='type',
            field=models.CharField(choices=[('delay', 'delay'), ('group', 'group'), ('email', 'email')], max_length=50, verbose_name='type'),
        ),
    ]
