# Generated by Django 4.0.4 on 2022-05-30 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_channel_account'),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='environments',
            field=models.ManyToManyField(editable=False, related_name='pipelines', to='configuration.environment'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestep',
            unique_together={('pipeline', 'order')},
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('trigger', models.CharField(editable=False, max_length=200, verbose_name='trigger')),
                ('contact_key', models.CharField(editable=False, max_length=100, verbose_name='contact key')),
                ('event_payload', models.JSONField(default=dict, editable=False, verbose_name='event payload')),
                ('pipeline_data', models.JSONField(default=dict, verbose_name='pipeline data')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account')),
                ('environment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.environment', verbose_name='environment')),
                ('pipeline', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='pipelines.pipeline', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'pipeline run',
                'verbose_name_plural': 'pipeline runs',
            },
        ),
    ]
