# Generated by Django 4.0.3 on 2022-04-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
    ]
