# Generated by Django 4.1 on 2022-09-04 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
