# Generated by Django 4.0.4 on 2022-05-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_account_emailchannel_account_environment_account'),
        ('pipelines', '0002_email_autogenerate_text_alter_pipelinestep_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='autogenerate_text',
            field=models.BooleanField(default=True, help_text='Generate text automatically from html template', verbose_name='autogenerate text'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.emailchannel', verbose_name='email channel'),
        ),
        migrations.AlterField(
            model_name='email',
            name='html_body',
            field=models.TextField(verbose_name='html body message'),
        ),
        migrations.AlterField(
            model_name='email',
            name='only_unread',
            field=models.BooleanField(default=True, help_text='Send notification only if user have not seen it yet', verbose_name='unread only'),
        ),
        migrations.AlterField(
            model_name='email',
            name='text_body',
            field=models.TextField(help_text="Text used on clients that don't support html emails", verbose_name='plain text message'),
        ),
    ]
