# Generated by Django 4.0.4 on 2022-05-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_emailchannel_name'),
        ('pipelines', '0003_alter_email_autogenerate_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='account',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='account',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='pipeline',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipelines.pipeline', verbose_name='pipeline'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='type',
            field=models.CharField(choices=[('delay', 'delay'), ('group', 'group'), ('email', 'email')], editable=False, max_length=50, verbose_name='type'),
        ),
    ]
