# Generated by Django 4.0.4 on 2022-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_remove_pipelinerun_trigger_alter_pipelinestep_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinelog',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'debug'), ('INFO', 'info'), ('WARNING', 'warning'), ('ERROR', 'error')], default='INFO', max_length=10, verbose_name='level'),
        ),
    ]
