# Generated by Django 4.0.4 on 2022-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_alter_pipelinelog_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(blank=True, help_text="From address for this step. Overrides channel's default from address", max_length=200, verbose_name='from email'),
        ),
    ]
