# Generated by Django 4.0.5 on 2022-06-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_rename_pipeline_pipelinerun_pipeline_revision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestep',
            options={'verbose_name': 'pipeline step', 'verbose_name_plural': 'pipeline steps'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='pipelinestep',
            order_with_respect_to='pipeline',
        ),
    ]
