# Generated by Django 4.0.5 on 2022-06-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_alter_pipelinestep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestep',
            options={'ordering': ('pipeline', 'order'), 'verbose_name': 'pipeline step', 'verbose_name_plural': 'pipeline steps'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='pipelinestep',
            order_with_respect_to=None,
        ),
    ]
