# Generated by Django 4.0.5 on 2022-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_alter_pipelinestep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinelog',
            options={'ordering': ('date',), 'verbose_name': 'pipeline log', 'verbose_name_plural': 'pipeline logs'},
        ),
        migrations.AlterModelOptions(
            name='pipelinerun',
            options={'ordering': ('-start',), 'verbose_name': 'pipeline run', 'verbose_name_plural': 'pipeline runs'},
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='group_key',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='group_key'),
        ),
        migrations.AddConstraint(
            model_name='pipelinerun',
            constraint=models.UniqueConstraint(fields=('contact_key', 'pipeline_revision', 'group_key'), name='unique group'),
        ),
    ]
