# Generated by Django 4.1 on 2022-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_alter_pipelinelog_options_alter_pipelinerun_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='key',
            field=models.SlugField(max_length=150, verbose_name='grouping key'),
        ),
    ]
