# Generated by Django 4.0.5 on 2022-08-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_alter_pushchannel_firebase_credentials'),
        ('pipelines', '0010_alter_group_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('pipelinestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipelines.pipelinestep')),
                ('only_unread', models.BooleanField(default=True, help_text='Send notification only if user have not seen it yet', verbose_name='unread only')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('url', models.URLField(verbose_name='url')),
                ('push_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.pushchannel', verbose_name='push channel')),
            ],
            options={
                'verbose_name': 'push template',
                'verbose_name_plural': 'push templates',
            },
            bases=('pipelines.pipelinestep',),
        ),
    ]
