name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --upgrade-strategy eager -r requirements-dev.txt
    
    - name: Run Tests
      run: |
        coverage run --source='.' manage.py test
        coverage report
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov 
  
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps: 
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only --build-arg BUILD_VERSION=$(date +'%Y%m%d%H%M%S').${{ github.ref_name }}.$(git rev-parse --short HEAD) --build-arg GIT_REV=${{ github.sha }}
    - name: Rollbar deploy
      uses: rollbar/github-deploy-action@2.1.1
      with:
        environment: 'production'
        version: ${{ github.sha }}
      env:
        ROLLBAR_USERNAME: ${{ github.actor }}
